---
name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  init:
    uses: PhilippAuch/workflows/.github/workflows/init.yaml@main

  build:
    uses: PhilippAuch/workflows/.github/workflows/buildGradleDocker.yaml@main
    strategy:
      matrix:
        service: ['stock', 'target']
    with:
      subfolder: './${{ matrix.service }}-service/'
      imageNameAddon: '-${{ matrix.service }}-service'

  deploy:
    uses: PhilippAuch/workflows/.github/workflows/deployTemplate.yaml@main
    needs: build
    with:
      subfolder: './kubernetes/'
    secrets:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
