---
name: Create Update Branch NPM

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'
    outputs:
      branchName:
        description: 'Name of the created branch'
        value: ${{ jobs.create-branch.outputs.outputName }}

env:
  GITHUB-MAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  create-branch:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write

    outputs:
      outputName: ${{ steps.outputbranchname.outputs.branchname }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: create new Branch
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "$GITHUB_MAIL"
            git checkout -b update-branch-${{ github.run_id }}

      - name: do the npm update
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: |
            cd ${{ inputs.subfolder }}
            npm install -S
            npm outdated || true
            npm update -S
            npm install -S
            npm outdated || true
            npx npm-check-updates -u --peer
            npm install -S
            npm update -S
            npm install -S

      - name: git add and push to remote
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            git push -u origin update-branch-${{ github.run_id }}
            git add -A
            git commit -m "Update dependencies"
            git push -u origin update-branch-${{ github.run_id }}

      - name: create PR
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update-branch-${{ github.run_id }}
          target_branch: main
          title: Update Frontend PR
          body: '**Automated pull request**'
          label: update

      - id: outputbranchname
        run: echo branchname=update-branch-${{github.run_id}} >> $GITHUB_OUTPUT
