---
name: Initialization

on:
  workflow_call:
    inputs:
      branch-name:
        required: false
        type: string
        default: ${{ github.ref }}
  push:
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  print-env:
    runs-on: ubuntu-22.04

    steps:
      - run: env

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: "0"

      - name: Check .env file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: ".env"

      - uses: cardinalby/export-env-action@2.1.0
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          envFile: '.env'
          expand: 'true'
          expandWithJobEnv: 'true'
          export: 'true'

      - run: env

  validate-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: "0"

      - name: Download custom yaml rules
        run: curl https://raw.githubusercontent.com/PhilippAuch/workflows/main/rules.yaml -o ./rules.yaml

      - name: Validate YAML file
        run: yamllint -s -c ./rules.yaml -f github .
