name: Initialization

on:
  workflow_call:

jobs:
  print-env:
    runs-on: ubuntu-22.04

    steps:
      - run: env

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'
          expand: 'true'
          expandWithJobEnv: 'true'
          export: 'true'

      - run: env