name: Initialization

on:
  workflow_call:

jobs:
  print-env:
    runs-on: ubuntu-22.04

    steps:
      - run: env

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: "0"

      - name: Check .env file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: ".env"

      - uses: cardinalby/export-env-action@2.1.0
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          envFile: '.env'
          expand: 'true'
          expandWithJobEnv: 'true'
          export: 'true'

      - run: env