---
name: Initialization

on:
  workflow_call:
    inputs:
      branch-name:
        required: false
        type: string
        default: ${{ github.ref }}

env:
  REGISTRY: ghcr.io

jobs:
  print-env-and-check-yaml:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - run: env

      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: '0'

      - name: Check .env file existence
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: '.env'

      - uses: cardinalby/export-env-action@2.2.2
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          envFile: '.env'
          expand: 'true'
          expandWithJobEnv: 'true'
          export: 'true'

      - run: env

      - name: Download custom yaml rules
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            curl https://raw.githubusercontent.com/PhilippAuch/workflows/main/rules.yaml -o ./rules.yaml

      - name: Validate YAML file
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            yamllint -s -c ./rules.yaml -f github .
