---
name: Publish the latest git release

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'

jobs:
  publish-release:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tagging_dryrun
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true

      - name: Write version to file
        uses: dolittle/write-version-to-file-action@v2.1.2
        with:
          version: '${{ steps.tagging_dryrun.outputs.new_tag }}'
          path: ./version.json
          user-email: build@githubaction.com
          user-name: build-githubaction
          merge-strategy: merge

      - name: Git pull & push
        run: |
          git pull
          git push
          git rev-parse main
          git show

      - name: Override GITHUB_ENV with new SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse main)
          echo "NEW_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tagging
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ env.NEW_SHA }}
          release_branches: main
          dry_run: false

      - uses: ncipollo/release-action@v1.14.0
        with:
          commit: '${{ env.NEW_SHA }}'
          generateReleaseNotes: true
          tag: '${{ steps.tagging.outputs.new_tag }}'
