---
name: Publish the latest git release

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'

jobs:
  publish-release:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name=='push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.4.0
        id: tagging
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ steps.tagging.outputs.new_tag }}'
          prerelease: false
