---
name: Publish the latest git release

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'

jobs:          
  publish-release:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tagging_dryrun
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true

      - name: Write version to file
        uses: dolittle/write-version-to-file-action@v2.1.2
        with:
          version: '${{ steps.tagging_dryrun.outputs.new_tag }}'
          path: ./version.json
          user-email: build@githubaction.com
          user-name: build-githubaction
          merge-strategy: merge

      - name: Wait 10 seconds
        run: sleep 10

      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: '0'
          ref: 'main'

      - name: Override GITHUB_ENV with new SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse main)
          echo "NEW_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tagging
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ env.NEW_SHA }}
          release_branches: main
          dry_run: false

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ steps.tagging.outputs.new_tag }}'
          prerelease: false
