---
name: Publish to npm-repo.auch.ovh

on:
  workflow_call:

jobs:
  publish-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    timeout-minutes: 180
    runs-on: self-hosted
    if: |
      ((github.event_name == 'workflow_dispatch' || github.event_name=='push' ||
      github.event_name == 'schedule') && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: "0"
          persist-credentials: true

      - name: Git pull
        run: git pull

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "lts/*"
          token: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://npm-repo.auch.ovh"

      - name: Clean install dependencies
        run: npm ci

      - name: Debug npm config
        run: cat /home/pauch/actions-runner/_work/_temp/.npmrc

      - name: Build package
        run: npm run build

      - name: Publish version
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: "MzAwZDc0YmVmNDgzMThlZDQyYTc2OTRlMGMwYjgyNTI6OTE3ZmYwZmQ2YmNiYjQ0N2UwY2ZjNTE2MDNkN2UzZDY0ZmM3N2FhZjZjYTJmZjAzMDYxNWRk"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
