---
name: Restart TrueNAS App

on:
  workflow_call:
    inputs:
      app_name:
        description: "App name to restart"
        required: true
        type: string
    secrets:
      TRUENAS_API_KEY:
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  restart-app:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - name: Restart TrueNAS App
        uses: gurumitts/truenas-app-action@v4
        with:
          truenas-url: "https://nas.auch.ovh"
          api-key: ${{ secrets.TRUENAS_API_KEY }}
          app-name: ${{ inputs.app_name }}
          action: "restart"
