---
name: Analyze with sonar

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'
      branch-name:
        required: false
        type: string
        default: ${{ github.ref }}
      sonar-project-key:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  analyze:
    timeout-minutes: 60
    env:
      SONAR: ${{ secrets.SONAR_TOKEN }}
    if: ((github.event_name == 'workflow_dispatch' || github.event_name=='push') && github.ref == 'refs/heads/main') || github.event_name == 'schedule'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: '0'

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v8

      - name: Run sonarqube
        uses: nick-fields/retry@v3.0.0
        if: env.SONAR != null
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: >-
            cd ${{inputs.subfolder}} && sonar-scanner \
                                          -Dsonar.projectKey=${{inputs.sonar-project-key}} \
                                          -Dsonar.sources=. \
                                          -Dsonar.host.url=https://sonarqube.philipp-auch.de/ \
                                          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
                                          -Dsonar.exclusions="test/*, kubernetes/*"

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        if: env.SONAR != null
        timeout-minutes: 5
        with:
          scanMetadataReportFile: ${{inputs.subfolder}}.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.philipp-auch.de
