name: Test Gradle YAML

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: "./"

jobs:
  gradle-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'

      - name: Run build with Gradle Wrapper
        run: ${{ inputs.subfolder }}gradlew -p ${{ inputs.subfolder }} clean build test