name: Test Gradle YAML

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: "./"

jobs:
  gradle-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ${{ inputs.subfolder }}gradlew clean build test