---
name: Run Tests with Node

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'
      branch-name:
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      GH_SSH_PRIVATE:
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  node-test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: '0'

      - uses: webfactory/ssh-agent@v0.8.0
        env:
          GH_SSH: ${{ secrets.GH_SSH_PRIVATE }}
        if: env.GH_SSH != null
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE }}

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{ inputs.subfolder }} && npm install

      - name: Run test
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{ inputs.subfolder }} && npm run test
