---
name: Run Tests with Node

on:
  workflow_call:
    inputs:
      subfolder:
        required: false
        type: string
        default: './'
      branch-name:
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      GH_SSH_PRIVATE:
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  node-test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: '0'

      - uses: webfactory/ssh-agent@v0.9.0
        env:
          GH_SSH: ${{ secrets.GH_SSH_PRIVATE }}
        if: env.GH_SSH != null
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE }}

      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{ inputs.subfolder }} && npm ci

      - name: Check if playwright is used
        id: check_playwright
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: '${{ inputs.subfolder }}playwright.config.ts'

      - name: Install playwright
        if: steps.check_playwright.outputs.files_exists == 'true'
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{ inputs.subfolder }} && npx playwright install --with-deps

      - name: Run test
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{ inputs.subfolder }} && npm run test

      - name: Save playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.check_playwright.outputs.files_exists == 'true' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
